import os
import pandas as pd

configfile: "config/config.yml"

df = pd.read_table(config["samples"]["file"])
runs = list(df["run"])

raw_path = config["paths"]["raw"]
trimmed_path = config["paths"]["trimmed"]
fastp_report_path = config["paths"]["fastp_report"]
quant_path = config["paths"]["quant"]
ref_species = config["reference"]["species"]
ref_build = config["reference"]["build"]
ref_release = config["reference"]["release"]
genome = config["reference"]["genome"]
transcriptome = config["reference"]["transcriptome"]
annotation = config["reference"]["annotation"]
salmon_index = config["reference"]["salmon_index"]
gentrome = config["reference"]["gentrome"]
decoys = config["reference"]["decoys"]

print("Number of runs:", len(runs))

rule all:
    input:
        expand(
            os.path.join(raw_path, "{accession}_1.fastq.gz"),
            accession=runs
        ),
        expand(
            os.path.join(raw_path, "{accession}_2.fastq.gz"),
            accession=runs
        )

include: "rules/sra_download.smk"
include: "rules/fastp.smk"
include: "rules/reference.smk"
include: "rules/salmon.smk"
