import os
import pandas as pd

configfile: "config/config.yml"

df = pd.read_table(config["samples"]["file"])
runs = list(df["run"])

raw_path = config["paths"]["raw"]
trimmed_path = config["paths"]["trimmed"]
fastp_report_path = config["paths"]["fastp_report"]

print("Number of runs:", len(runs))

rule all:
    input:
        expand(
            os.path.join(raw_path, "{accession}_1.fastq.gz"),
            accession=runs
        ),
        expand(
            os.path.join(raw_path, "{accession}_2.fastq.gz"),
            accession=runs
        )

include: "rules/sra_download.smk"
include: "rules/fastp.smk"
