samples:
  file: "config/samples.tsv"

paths:
  raw: "data/raw_data"
  trimmed: "data/trimmed"
  fastp_report: "output/fastp"
  quant: "data/quant"
  contamination_tmp: "data/tmp/contamination_qc"
  contamination_qc: "output/contamination_qc" 
  qc_summary: "output/qc"
  qc: "docs/qc"

reference:
  species: "homo_sapiens"
  build: "GRCh38"
  release: 116
  root: "data/reference"

  genome: "data/reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
  transcriptome: "data/reference/Homo_sapiens.GRCh38.cdna.all.fa.gz"
  annotation: "data/reference/Homo_sapiens.GRCh38.116.gtf.gz"

  gentrome: "data/reference/gentrome.fa.gz"
  decoys: "data/reference/decoys.txt"
  salmon_index: "data/reference/salmon_index"

  rrna: "data/reference/qc/rrna/all_rrna.fa"
  hbrna: "data/reference/qc/hbrna/hbrna.fa"

params:
  sra_download:
    extra: "--split-files"

  fastp:
    extra: "--n_base_limit 1 
            --average_qual 30 
            --length_required 35
            --correction 
            --overrepresentation_analysis 
            --disable_trim_poly_g"
    adapters: "--detect_adapter_for_pe"

  salmon:
    quant:
      extra: "--incompatPrior 0.0
              --numGibbsSamples 100 
              --thinningFactor 16 
              --gcBias 
              --seqBias 
              --softclip"

    index:
      extra: "--keepDuplicates"

  multiqc:
    extra: ""
    use_input_files_only: false